const fs=require('fs'),vm=require('vm'),assert=require('assert'),{createCanvas}=require('@napi-rs/canvas');
require('@napi-rs/canvas').GlobalFonts.registerFromPath('qa/pdf-regular.ttf','AstraPDF');require('@napi-rs/canvas').GlobalFonts.registerFromPath('qa/pdf-bold.ttf','AstraPDF');
const target=process.argv[2]||'output125/escalas-app-cbsi-v11-2-4-homologacao-astra.html';
const html=fs.readFileSync(target,'utf8');let source=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const data=new Map(),nodes=new Map(),events={};let failKey=null;
const classList={add(){},remove(){},toggle(){},contains(){return false}};
function node(id){if(!nodes.has(id))nodes.set(id,{textContent:'',value:'',className:'',hidden:false,classList,style:{},innerHTML:'',appendChild(){},setAttribute(){},querySelector(){return node('child')},addEventListener(n,f){events[id+':'+n]=f},focus(){},remove(){}});return nodes.get(id)}
const localStorage={get length(){return data.size},key:i=>[...data.keys()][i],getItem:k=>data.has(k)?data.get(k):null,setItem(k,v){if(failKey&&(!failKey.key||k===failKey.key)){if(failKey.once)failKey=null;throw new Error('QuotaExceededError simulado')}data.set(k,String(v))},removeItem:k=>data.delete(k)};
const document={getElementById:node,querySelectorAll:()=>[],querySelector:()=>null,createElement:t=>t==='canvas'?createCanvas(1,1):node('new'),body:node('body'),documentElement:node('html'),addEventListener(){}};
const sandbox={console:{log(){},info(){},error(){}},Date,Math,Number,String,Array,Object,JSON,Set,Map,Promise,Uint8Array,Blob,crypto:require('crypto').webcrypto,document,navigator:{},atob:s=>Buffer.from(s,'base64').toString('binary'),location:{protocol:'file:'},setTimeout:()=>0,clearTimeout(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},localStorage};sandbox.window=sandbox;sandbox.addEventListener=()=>{};
source=source.replace('  selfTestResult=runCoreSelfTests();',`  window.TEST={run: function(code){return eval(code);}};return;\n  selfTestResult=runCoreSelfTests();`);
vm.createContext(sandbox);vm.runInContext(source,sandbox);
const run=code=>sandbox.TEST.run(code),results=[];
function test(name,fn){try{fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.message});}}
function eq(code,expected){assert.deepStrictEqual(JSON.parse(JSON.stringify(run(code))),expected)}
const fixture=`state.segunda=new Date(2026,8,14);state.semanaId=weekId(state.segunda);state.diaSel=0;state.pessoas=[{id:'per_person_001',nome:'José Silva'},{id:'per_person_002',nome:'Jose Silva'}];state.postos=[{id:'pst_station_001',nome:'Posto de teste',local:'Dados fictícios de homologação',turnos:[{id:'shf_admin_001',label:'ADM',inicio:'07:30',fim:'17:18',carga:''},{id:'shf_night_001',label:'Noite',inicio:'22:00',fim:'06:00',carga:''}]}];state.atribuicoes={};historyCache={};storageBackend='local';memoryStorage={};localStorage.clearUnused;`;
function reset(){data.clear();failKey=null;if(process.env.BASELINE!=='1')run('storageKeyErrors=Object.create(null)');run(fixture)}
const key=(d,t='shf_admin_001')=>`pst_station_001__${d}__${t}`;
function assign(d,he=0,p='per_person_001',t='shf_admin_001'){run(`state.atribuicoes[${JSON.stringify(key(d,t))}]={tipo:'pessoas',pessoaIds:['${p}'],heMinutos:${he}}`)}
function proposal(d,he=0,t='shf_admin_001'){return `validarPropostaAtribuicao('${key(d,t)}',{tipo:'pessoas',pessoaIds:['per_person_001'],heMinutos:${he}})`}
for(const k of ['cbsi_theme_v11','cbsi_theme_v10','cbsi_theme_v9'])for(const theme of ['dark','light'])test(k+' legado '+theme,()=>{reset();data.set(k,theme);data.set('cbsi_v11_pessoas',JSON.stringify([{id:'per_person_001',nome:'Preservado'}]));const saved=data.get('cbsi_v11_pessoas');run('initTheme()');eq('storageBackend','local');assert.equal(data.get('cbsi_theme_v11'),JSON.stringify(theme));assert.equal(data.get('cbsi_v11_pessoas'),saved);eq("storageGet(KEYS.pessoas,[])[0].nome",'Preservado')});
test('Chave inválida isolada não afeta outras',()=>{reset();data.set('cbsi_v11_pessoas','{bad');data.set('cbsi_v11_postos','[]');eq('storageGet(KEYS.pessoas,[])',[]);eq('storageBackend','local');eq('storageGet(KEYS.postos,[])',[]);eq("storageSet(KEYS.postos,[{id:'p',nome:'Teste',turnos:[]}])",true);assert.equal(data.get('cbsi_v11_pessoas'),'{bad')});
if(process.env.BASELINE==='1'){console.log(JSON.stringify(results,null,2));fs.writeFileSync('qa/bug-before.json',JSON.stringify(results,null,2));process.exit(0)}
test('JSON de tema atual mantém local',()=>{reset();data.set('cbsi_theme_v11','"dark"');run('initTheme()');eq('storageBackend','local');assert.equal(data.get('cbsi_theme_v11'),'"dark"')});
test('Tema inválido preservado e fallback visual seguro',()=>{reset();data.set('cbsi_theme_v11','{broken');data.set('cbsi_theme_v10','dark');run('initTheme()');eq('storageBackend','local');assert.equal(data.get('cbsi_theme_v11'),'{broken');eq("storageGet('cbsi_theme_v10',null)",'dark')});
test('Tema com tipo JSON inválido isolado',()=>{reset();data.set('cbsi_theme_v11','{}');eq("storageGet('cbsi_theme_v11',null)",null);eq('storageBackend','local');assert.equal(data.get('cbsi_theme_v11'),'{}')});
test('Texto dark não é permitido em chave estruturada',()=>{reset();data.set('cbsi_v11_pessoas','dark');eq('storageGet(KEYS.pessoas,[])',[]);eq('storageBackend','local');eq('storageSet(KEYS.pessoas,[])',false);assert.equal(data.get('cbsi_v11_pessoas'),'dark')});
for(const [key,raw] of [['pessoas','null'],['postos','{}'],['semanas','[]'],['meta','42'],['snapshots','"bad"']])test('Tipo de chave '+key+' isolado',()=>{reset();data.set('cbsi_v11_'+key,raw);run(`storageGet(KEYS.${key},null)`);eq('storageBackend','local');assert(run(`!!storageKeyErrors[KEYS.${key}]`))});
test('Espelho mantém última leitura válida',()=>{reset();run("storageSet(KEYS.pessoas,[{id:'per_person_001',nome:'Original'}]);storageGet(KEYS.pessoas,[])");data.set('cbsi_v11_pessoas','{bad');eq('storageGet(KEYS.pessoas,[])[0].nome','Original');eq('storageSet(KEYS.pessoas,[])',false)});
test('Hidratação aceita tema legado sem gravar',()=>{reset();data.set('cbsi_theme_v9','dark');data.set('cbsi_v11_pessoas','{bad');data.set('cbsi_v11_postos','[]');const before=JSON.stringify([...data]);run('hydrateStorageMirror()');assert.equal(JSON.stringify([...data]),before);eq("memoryStorage.cbsi_theme_v9",'dark');eq('storageBackend','local');eq('memoryStorage[KEYS.postos]',[])});
test('Leitura não migra na sessão bloqueada',()=>{reset();data.set('cbsi_theme_v11','dark');run('sessionReadOnly=true;initTheme()');assert.equal(data.get('cbsi_theme_v11'),'dark');eq('storageBackend','local');run('sessionReadOnly=false')});
test('Falha real getItem ativa fallback preservando espelho',()=>{reset();run("storageSet(KEYS.pessoas,[{id:'per_person_001',nome:'Original'}])");const getter=localStorage.getItem;localStorage.getItem=()=>{throw new Error('SecurityError simulado')};try{eq('storageGet(KEYS.pessoas,[])[0].nome','Original');eq('storageBackend','memory')}finally{localStorage.getItem=getter}});
test('Quota na migração é falha real, preserva tema bruto',()=>{reset();data.set('cbsi_theme_v11','dark');failKey={key:'cbsi_theme_v11'};run('initTheme()');eq('storageBackend','memory');assert.equal(data.get('cbsi_theme_v11'),'dark')});
test('Diário corrompido não muda backend nem é apagado',()=>{reset();data.set('cbsi_v11_transaction','{bad');run('recoverTransaction()');eq('storageBackend','local');assert.equal(data.get('cbsi_v11_transaction'),'{bad');eq('storeCorePackAtomic(currentDataPack())',false)});
test('Diário duplicado rejeitado antes de qualquer gravação',()=>{reset();data.set('cbsi_v11_transaction',JSON.stringify(Array.from({length:4},()=>({key:'cbsi_v11_pessoas',raw:'[]'}))));const before=JSON.stringify([...data]);run('recoverTransaction()');assert.equal(JSON.stringify([...data]),before);eq('storageBackend','local')});
test('Migração automática não substitui chave danificada',()=>{reset();data.set('cbsi_v11_pessoas','{bad');eq('storeCorePackAtomic(currentDataPack())',false);assert.equal(data.get('cbsi_v11_pessoas'),'{bad')});
run('renderTudo=function(){};renderDataCenter=function(){};renderAudit=function(){};toast=function(){}');
test('Restauração validada pode substituir chave danificada',()=>{reset();data.set('cbsi_v11_pessoas','{bad');run('storageGet(KEYS.pessoas,[])');eq('persistWholePack(currentDataPack())',true);assert.equal(JSON.parse(data.get('cbsi_v11_pessoas')).length,2);eq('storageBackend','local');eq('!!storageKeyErrors[KEYS.pessoas]',false)});
test('Inicialização de dados vazia sem modo temporário',()=>{reset();run('state.postos=[];state.pessoas=[];historyCache={};recoverTransaction();initTheme();carregarLocal()');eq('storageBackend','local');eq('state.postos',[]);eq('state.pessoas',[])});
test('Inicialização com tema legado preserva conjunto estruturado',()=>{reset();run('storeCorePackAtomic(currentDataPack());storageSet(KEYS.meta,{schema:113})');data.set('cbsi_theme_v11','dark');const before=['postos','pessoas','semanas','feriados'].map(k=>data.get('cbsi_v11_'+k));run('recoverTransaction();initTheme();carregarLocal()');eq('storageBackend','local');assert.deepStrictEqual(['postos','pessoas','semanas','feriados'].map(k=>data.get('cbsi_v11_'+k)),before)});
test('BroadcastChannel detecta outra sessão antes de iniciar (simulado)',()=>{reset();const timer=sandbox.setTimeout;let pending=[];sandbox.setTimeout=f=>{pending.push(f);return 1};sandbox.BroadcastChannel=class {constructor(){sandbox.channel=this}postMessage(m){this.sent=m}};try{run('window.startCount=0;acquireSession(function(){window.startCount++})');sandbox.channel.onmessage({data:'hello'});pending.forEach(f=>f());eq('sessionReadOnly',true);eq('startCount',0);assert.equal(sandbox.channel.sent,'occupied')}finally{sandbox.setTimeout=timer;delete sandbox.BroadcastChannel;run('sessionReadOnly=false')}});
test('Evento de escrita externa bloqueia persistência (simulado)',()=>{reset();let listener;const adder=sandbox.addEventListener;sandbox.addEventListener=(event,fn)=>{if(event==='storage')listener=fn};try{run('acquireSession(function(){})');listener({key:'cbsi_v11_semanas'});eq('sessionReadOnly',true);eq('storageSet(KEYS.pessoas,[])',false)}finally{sandbox.addEventListener=adder;run('sessionReadOnly=false')}});
fs.writeFileSync('qa/hotfix-results.json',JSON.stringify({passed:results.filter(x=>x.ok).length,total:results.length,results},null,2));console.log(JSON.stringify({passed:results.filter(x=>x.ok).length,total:results.length,failures:results.filter(x=>!x.ok)},null,2));if(results.some(x=>!x.ok))process.exitCode=1;
